name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "luigilopesz"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: luigilopesz/pf_zambom:${{ github.sha }}

    - name: Executar comandos remotos via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: >
          docker stop pf_zambom || true &&
          docker rm --force pf_zambom || true &&
          docker run -d -p 8080:8080 -e mongodb_string_pf=${{ secrets.mongodb_string_pf }} --name pf_zambom --network=rede luigilopesz/pf_zambom:${{ github.sha }}


